### PR TITLE
Fix a Markdown link syntax

### PR DESCRIPTION
**Pull request by tzi**
Hi!

The PR is a small fix for a Markdown link syntax.

Thanks for sharing this project!
Cheers,
Thomas.

### CODE REVIEW

**Comment by tzi** [comment]
The travis-ci failed with this message:

    Zuul tried to run tests in saucelabs, however no saucelabs credentials were provided.

**Comment by vvo** [comment]
Thanks, where are you using in-viewport?

**Comment by tzi** [comment]
We use it through `lazyload` on http://mapado.com.
We digged the documentation, cause we had a hard time to implement the custom container ;)
But everything's fine now! 

Thanks again!
Thomas.

**Comment by vvo** [comment]
Arg, sorry you had problems using the custom container part of lazyload, how could we improve the documentation? As you are a user maybe you have ideas.

Fun fact: I also work at https://www.algolia.com/ and you seem to be a customer.

**Comment by tzi** [comment]
Perhaps, we can explain in the documentation when we need to define a `container`.
Our use case was a `popin` with its own scroll.
We didn't understood that to detect when the images was visible in the screen, we could not use the document container if they had a parent with scroll.
Is there any way to detect this parent automatically?

We can also precise that the lazy load with a custom container could not been defined in the head, obviously, so you can not use it easily with the `onload` attribute. 

Cheers,
Thomas.

**Pull request merged**
